import { existsSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import { spawn, type ChildProcess } from "node:child_process";
import type { Browser, BrowserContext, Page } from "playwright-core";
import type { Observation } from "../src/shared/types.js";
import { OzonBrowserAdapter } from "../src/server/adapters/ozon-browser.js";
import { loadPlaywright } from "../src/server/utils/playwright-runtime.js";

const OZON_ORIGIN = "https://www.ozon.ru";
const COMPOSER_PATH = "/api/composer-api.bx/page/json/v2";
const SEARCH_PATH = "/search/";
const ALLOWED_SEARCH_PARAMETERS = new Set(["text", "from_global", "page"]);
const DEFAULT_PROFILE = join(
  process.env.LOCALAPPDATA?.trim() || join(homedir(), "AppData", "Local"),
  "RatingsCollector",
  "ozon-profile"
);
const CDP_PORT = 8766;

type BrowserFetchResult = {
  status: number;
  statusText: string;
  headers: Array<[string, string]>;
  body: string;
};

export type CompanionOzonResult = Pick<
  Observation,
  "listingId" | "brand" | "canonicalUrl" | "product" | "reviews" | "rating" | "capturedAt"
> & { status: "ok" | "no_reviews" | "needs_review" };

export type ResidentialOzonCollectorOptions = {
  profileDirectory?: string;
  chromeExecutable?: string;
  connectOverCDP?: typeof import("playwright-core")["chromium"]["connectOverCDP"];
  launchPersistentContext?: typeof import("playwright-core")["chromium"]["launchPersistentContext"];
  now?: () => Date;
};

/**
 * Accepts only the one Ozon endpoint generated by OzonBrowserAdapter. The
 * companion is intentionally not a general-purpose localhost proxy.
 */
export function assertAllowedOzonComposerUrl(input: string): URL {
  const endpoint = new URL(input);
  if (endpoint.origin !== OZON_ORIGIN || endpoint.pathname !== COMPOSER_PATH) {
    throw new TypeError("Local companion only permits the Ozon composer search endpoint");
  }
  if ([...endpoint.searchParams.keys()].some((key) => key !== "url") || endpoint.searchParams.getAll("url").length !== 1) {
    throw new TypeError("Unexpected Ozon composer parameter");
  }
  const nested = endpoint.searchParams.get("url");
  if (!nested || !nested.startsWith("/") || nested.startsWith("//")) {
    throw new TypeError("Ozon composer search URL must be a relative path");
  }
  const search = new URL(nested, OZON_ORIGIN);
  if (search.origin !== OZON_ORIGIN || search.hash) {
    throw new TypeError("Local companion only permits an exact Ozon path");
  }
  const exactProduct = /^\/product\/[a-z0-9-]*\d{5,}\/$/i.test(search.pathname) && !search.search;
  if (exactProduct) return endpoint;
  if (search.pathname !== SEARCH_PATH) {
    throw new TypeError("Local companion only permits Ozon product search or an exact product card");
  }
  if ([...search.searchParams.keys()].some((key) => !ALLOWED_SEARCH_PARAMETERS.has(key))) {
    throw new TypeError("Unexpected Ozon search parameter");
  }
  const text = search.searchParams.get("text")?.normalize("NFKC").trim();
  if (!text || text.length > 160) throw new TypeError("Ozon search brand is invalid");
  const page = search.searchParams.get("page");
  if (page !== null && (!/^\d+$/.test(page) || Number(page) < 2 || Number(page) > 100)) {
    throw new TypeError("Ozon search page is outside the safe range");
  }
  return endpoint;
}

function requestUrl(input: URL | RequestInfo): string {
  if (input instanceof URL) return input.toString();
  if (typeof input === "string") return input;
  return input.url;
}

async function pageFetch(page: Page, input: URL | RequestInfo, init?: RequestInit): Promise<Response> {
  if (init?.method && init.method !== "GET") throw new TypeError("Local Ozon browser only permits GET");
  const url = assertAllowedOzonComposerUrl(requestUrl(input)).toString();
  const result = await page.evaluate(async (target): Promise<BrowserFetchResult> => {
    const response = await fetch(target, {
      method: "GET",
      credentials: "include",
      headers: {
        accept: "application/json",
        "accept-language": "ru-RU,ru;q=0.9"
      }
    });
    return {
      status: response.status,
      statusText: response.statusText,
      headers: [...response.headers.entries()],
      body: await response.text()
    };
  }, url);
  return new Response(result.body, {
    status: result.status,
    statusText: result.statusText,
    headers: result.headers
  });
}

export class ResidentialOzonCollector {
  private context?: Promise<BrowserContext>;
  private browser?: Browser;
  private chromeProcess?: ChildProcess;
  private operation = Promise.resolve();
  private readonly profileDirectory: string;
  private readonly chromeExecutable?: string;
  private readonly connectOverCDP?: ResidentialOzonCollectorOptions["connectOverCDP"];
  private readonly launchPersistentContext?: ResidentialOzonCollectorOptions["launchPersistentContext"];
  private readonly now: () => Date;

  constructor(options: ResidentialOzonCollectorOptions = {}) {
    this.profileDirectory = options.profileDirectory ?? DEFAULT_PROFILE;
    this.chromeExecutable = options.chromeExecutable;
    this.connectOverCDP = options.connectOverCDP;
    this.launchPersistentContext = options.launchPersistentContext;
    this.now = options.now ?? (() => new Date());
  }

  async collect(brands: readonly string[], region: string): Promise<CompanionOzonResult[]> {
    const work = this.operation.then(() => this.collectSequentially(brands, region));
    this.operation = work.then(() => undefined, () => undefined);
    return work;
  }

  async close(): Promise<void> {
    if (this.browser) await this.browser.close().catch(() => undefined);
    else if (this.context) await (await this.context).close().catch(() => undefined);
    this.chromeProcess?.kill();
    this.chromeProcess = undefined;
    this.browser = undefined;
    this.context = undefined;
  }

  private async browserContext(): Promise<BrowserContext> {
    if (!this.context) {
      const launching = (async () => {
        await mkdir(this.profileDirectory, { recursive: true });
        if (this.launchPersistentContext) {
          return this.launchPersistentContext(this.profileDirectory, {
            channel: "chrome", headless: false, locale: "ru-RU", viewport: { width: 1365, height: 900 }
          });
        }
        const chrome = this.chromeExecutable ?? findChromeExecutable();
        this.chromeProcess = spawn(chrome, [
          `--remote-debugging-address=127.0.0.1`,
          `--remote-debugging-port=${CDP_PORT}`,
          `--user-data-dir=${this.profileDirectory}`,
          "--no-first-run",
          "--no-default-browser-check",
          `${OZON_ORIGIN}/`
        ], { stdio: "ignore", windowsHide: false });
        await waitForCdp(CDP_PORT, this.chromeProcess);
        const connect = this.connectOverCDP
          ?? (await loadPlaywright()).chromium.connectOverCDP.bind((await loadPlaywright()).chromium);
        this.browser = await connect(`http://127.0.0.1:${CDP_PORT}`);
        const context = this.browser.contexts()[0];
        if (!context) throw new Error("Chrome did not expose its browser context");
        return context;
      })();
      this.context = launching;
      void launching.catch(() => {
        if (this.context === launching) this.context = undefined;
      });
    }
    return this.context;
  }

  private async collectSequentially(brands: readonly string[], region: string): Promise<CompanionOzonResult[]> {
    const context = await this.browserContext();
    const page = context.pages()[0] ?? await context.newPage();
    if (!page.url().startsWith(OZON_ORIGIN)) {
      await page.goto(`${OZON_ORIGIN}/`, { waitUntil: "domcontentloaded", timeout: 60_000 });
    }
    const adapter = new OzonBrowserAdapter({
      fetch: ((input, init) => pageFetch(page, input, init)) as typeof globalThis.fetch,
      now: this.now
    });
    const results: CompanionOzonResult[] = [];
    for (const brand of brands) {
      const context = { region, brands, signal: undefined };
      const refs = await adapter.discover(brand, context);
      for (const ref of refs) {
        const observation = await adapter.collect(ref, context);
        if (!["ok", "no_reviews", "needs_review"].includes(observation.status)) {
          throw new Error(`Ozon local collector returned unsupported status ${observation.status}`);
        }
        results.push({
          listingId: observation.listingId,
          brand: observation.brand,
          canonicalUrl: observation.canonicalUrl,
          product: observation.product,
          reviews: observation.reviews,
          rating: observation.rating,
          status: observation.status as CompanionOzonResult["status"],
          capturedAt: observation.capturedAt
        });
      }
    }
    return results;
  }
}

function findChromeExecutable(): string {
  const configured = process.env.RATINGS_CHROME_PATH?.trim();
  const candidates = [
    configured,
    process.env.PROGRAMFILES && join(process.env.PROGRAMFILES, "Google", "Chrome", "Application", "chrome.exe"),
    process.env["PROGRAMFILES(X86)"] && join(process.env["PROGRAMFILES(X86)"], "Google", "Chrome", "Application", "chrome.exe"),
    process.env.LOCALAPPDATA && join(process.env.LOCALAPPDATA, "Google", "Chrome", "Application", "chrome.exe")
  ].filter((value): value is string => Boolean(value));
  const executable = candidates.find(existsSync);
  if (!executable) throw new Error("Google Chrome не найден. Установите Chrome и повторите запуск.");
  return executable;
}

async function waitForCdp(port: number, process: ChildProcess): Promise<void> {
  const endpoint = `http://127.0.0.1:${port}/json/version`;
  for (let attempt = 0; attempt < 60; attempt += 1) {
    if (process.exitCode !== null) throw new Error("Chrome завершился до запуска локального сборщика");
    try {
      const response = await fetch(endpoint, { signal: AbortSignal.timeout(1_000) });
      if (response.ok) return;
    } catch { /* Chrome is still starting. */ }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error("Chrome не запустил локальное подключение за 15 секунд");
}
